name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Prune unused Docker resources
      run: sudo docker system prune -af  

    - name: Pull Docker image
      run: docker pull smokepaus/cftc-app:latest

    - name: Stop and remove any existing containers
      run: |
        sudo docker stop cftc-app-container || true
        sudo docker rm cftc-app-container || true

    - name: List Docker images
      run: sudo docker images

    - name: Run Docker container
      run: |
        sudo docker run -d -p 80:5000 --name cftc-app-container \
        -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
        -e EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }} \
        smokepaus/cftc-app:latest
    
    - name: Prune dangling images
      run: sudo docker image prune -f  

    - name: Cleanup Docker volumes
      run: sudo docker system prune -f --volumes  
