name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Prune unused Docker resources
        run: docker system prune -af 
      - name: Prune dangling images
        run: docker image prune -f 
      - name: Pull Docker image
        run: sudo docker pull smokepaus/cftc-app:latest
      - name: Delete old docker container
        run: sudo docker rm -f cftc-app-container || true
      - name: Run Docker container
        run: sudo docker run -d -p 80:5000 --name cftc-app-container smokepaus/cftc-app
