name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Prune unused Docker resources
      run: docker system prune -af 

    - name: Build the Docker image
      run: docker build -t smokepaus/cftc-app:latest .
    
    - name: Cleanup Docker
      run: docker system prune -f --volumes

    - name: List Docker images
      run: docker images

    - name: Push to Docker Hub
      run: docker push smokepaus/cftc-app:latest
