name: CI Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Prune unused Docker resources
      run: |
        docker system prune -af

    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build the Docker image
      run: |
        docker buildx build --cache-from=type=local,src=/tmp/.buildx-cache \
          -t smokepaus/cftc-app:latest .

    - name: List Docker images
      run: docker images

    - name: Push to Docker Hub
      run: docker push smokepaus/cftc-app:latest

