name: Build and Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smokepaus/cftc_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up the SSH Agent with your EC2 private key
      - name: Start SSH Agent and add EC2 key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Disable StrictHostKeyChecking for SSH (optional, for smoother connections)
      - name: Disable strict host key checking
        run: |
          echo "Host *" >> ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      # Pull the latest Docker image and restart the containers on EC2
      - name: Deploy Docker container on EC2
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            set -x  # Enable debug output
            docker pull smokepaus/cftc_app:latest
            docker-compose down
            docker-compose up -d
          EOF



