name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: smokepaus/cftc_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            docker-compose.yml
          target: "/home/ubuntu/"

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.5 
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/
            echo "Pulling latest Docker image..."
            docker pull smokepaus/cftc_app:latest || { echo 'Docker pull failed'; exit 1; }
            echo "Stopping and removing existing containers..."
            docker-compose down || { echo 'docker-compose down failed'; exit 1; }
            echo "Starting containers..."
            docker-compose up -d || { echo 'docker-compose up failed'; exit 1; }
          debug: true



