name: Build and Deploy

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smokepaus/cftc_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -x  # Enable debug output
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts  
          docker pull smokepaus/cftc_app:latest
          docker-compose down
          docker-compose up -d
        debug: true



