# This is a basic workflow to help you get started with Actions
name: CFTC analysis application

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job calles "build"
  build:
    # The type of runner that the job will run on 
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout the files
      uses: actions/checkout@v2

    - name: Set up Python 3.12.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.12.6

    - name: Install dependencies
      run: |
        make install 
        
    - name: Format
      run: |
        make format 
    
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
    
    
