name: CFTC Analysis Application Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Dash App to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.6

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run format
      run: |
        make format

    - name: Install Node.js (to install pm2)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # or any version compatible with your system

    - name: Install pm2
      run: |
        npm install pm2 -g

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          # Navigate to the target directory
          cd ${{ secrets.TARGET_DIR }}

          # Stop any existing Dash app (if running)
          pm2 stop dash-app || true

          # Pull the latest code
          git pull origin main

          # Install/update any dependencies on the server
          pip install -r requirements.txt

          # Start the Dash app (replace 'app.py' with your actual app name)
          pm2 start app_cftc.py --name cftc-app

    - name: Restart Web Server (Optional)
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          sudo systemctl restart nginx

    
